export const MEMBERS = [
  { id: "m15", name: "보아", team: "VD", role: "디렉터", group: "director" },
  { id: "m1",  name: "규호", team: "ID", role: "디렉터", group: "director" },
  { id: "m5",  name: "준구", team: "ID", role: "디렉터", group: "director" },
  { id: "m8",  name: "유진", team: "ID", role: "시니어 디자이너",   group: "staff" },
  { id: "m10", name: "현열", team: "ID", role: "시니어 디자이너",   group: "staff" },
  { id: "m2",  name: "진우", team: "ID", role: "디자이너",         group: "staff" },
  { id: "m3",  name: "다은", team: "ID", role: "디자이너",         group: "staff" },
  { id: "m6",  name: "태영", team: "ID", role: "디자이너",         group: "staff" },
  { id: "m7",  name: "경선", team: "ID", role: "디자이너",         group: "staff" },
  { id: "m9",  name: "준범", team: "ID", role: "프리랜서 디자이너", group: "staff" },
  { id: "m11", name: "수현", team: "VD", role: "디자이너",         group: "staff" },
  { id: "m12", name: "혜경", team: "VD", role: "디자이너",         group: "staff" },
  { id: "m13", name: "지민", team: "VD", role: "디자이너",         group: "staff" },
  { id: "m4",  name: "도영", team: "VD", role: "인턴",            group: "staff", inactive: true },
  { id: "m14", name: "정수", team: "ID", role: "인턴",            group: "staff" },
  { id: "m16", name: "여준", team: "ID", role: "인턴",            group: "staff" },
  { id: "m17", name: "민지", team: "VD", role: "인턴",            group: "staff" },
];

export const FLOW_TEAM_KEYS = {
  '보아': '',
  '규호': '',
  '준구': '',
  '유진': '',
  '현열': '',
  '진우': '',
  '다은': '',
  '태영': '',
  '경선': '',
  '준범': '',
  '수현': '',
  '혜경': '',
  '지민': '',
  '도영': '',
  '정수': '',
  '여준': '',
  '민지': '',
};
